name: EKS Cluster Shut Down
on:
  workflow_dispatch:
jobs:
  cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_CLUSTER_LOCATION }}

      - name: Shut Down EKS Cluster
        run: |
          aws eks --region "${{ vars.AWS_CLUSTER_LOCATION }}" delete-cluster --name "pt-${{ vars.AWS_CLUSTER_LOCATION }}"
