name: Full Performance Test
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Choose Cloud Provider'
        required: true
        type: choice
        default: Azure
        options:
          - Azure
          - AWS
          - GCP
      tyk_version:
        description: 'Tyk Gateway version'
        required: true
        type: string
        default: 'v5.7'
      tyk_profiler_enabled:
        description: 'Enabled Tyk Profiling'
        required: true
        type: boolean
        default: false

env:
  provider: ${{ inputs.cloud == 'Azure' && 'aks' || (inputs.cloud == 'AWS' && 'eks' || 'gke') }}

concurrency:
  group: ${{ inputs.cloud }}

jobs:
  performance_test:
    name: "${{ inputs.cloud }} full performance run on Tyk ${{ inputs.tyk_version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install wget
        if: ${{ inputs.tyk_profiler_enabled == true }}
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Configure AKS credentials
        if: ${{ inputs.cloud == 'Azure' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure AWS credentials
        if: ${{ inputs.cloud == 'AWS' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_CLUSTER_LOCATION }}

      - name: Authenticate into gcloud
        if: ${{ inputs.cloud == 'GCP' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gcloud CLI
        if: ${{ inputs.cloud == 'GCP' }}
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Install gcloud k8s auth component
        if: ${{ inputs.cloud == 'GCP' }}
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: "1.8.2"

      - name: Create Terraform Cloud descriptors
        run: |
          cp ${{ env.provider }}/terraform.cloud.tf.example ${{ env.provider }}/terraform.cloud.tf
          cp .github/${{ env.provider }}/deployments.tf deployments/terraform.cloud.tf
          cp .github/${{ env.provider }}/tests.tf tests/terraform.cloud.tf

      - name: Stand up AKS cluster
        if: ${{ inputs.cloud == 'Azure' }}
        run: |
          cd aks
          terraform init -upgrade
          terraform apply \
            --var="cluster_location=${{ vars.AZURE_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.AZURE_CLUSTER_MACHINE_TYPE }}" \
            --var="upstream_machine_type=${{ vars.AZURE_UPSTREAM_MACHINE_TYPE }}" \
            --var="tests_machine_type=${{ vars.AZURE_TEST_MACHINE_TYPE }}" \
            --auto-approve

      - name: Connect to AKS cluster
        if: ${{ inputs.cloud == 'Azure' }}
        run: |
          az aks get-credentials \
            --resource-group "pt-${{ vars.AZURE_CLUSTER_LOCATION }}" \
            --name "pt-${{ vars.AZURE_CLUSTER_LOCATION }}"

          kubectl config rename-context $(kubectl config current-context) performance-testing

      - name: Stand up EKS cluster
        if: ${{ inputs.cloud == 'AWS' }}
        run: |
          cd eks
          terraform init -upgrade
          terraform apply \
            --var="cluster_location=${{ vars.AWS_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.AWS_CLUSTER_MACHINE_TYPE }}" \
            --var="upstream_machine_type=${{ vars.AWS_UPSTREAM_MACHINE_TYPE }}" \
            --var="tests_machine_type=${{ vars.AWS_TEST_MACHINE_TYPE }}" \
            --auto-approve

      - name: Connect to EKS cluster
        if: ${{ inputs.cloud == 'AWS' }}
        run: |
          aws eks --region "${{ vars.AWS_CLUSTER_LOCATION }}" update-kubeconfig --name "pt-${{ vars.AWS_CLUSTER_LOCATION }}"

          kubectl config rename-context $(kubectl config current-context) performance-testing

      - name: Stand up GKE cluster
        if: ${{ inputs.cloud == 'GCP' }}
        run: |
          cd gke
          terraform init -upgrade
          terraform apply \
            --var="project=${{ secrets.GCP_PROJECT }}" \
            --var="cluster_location=${{ vars.GCP_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.GCP_CLUSTER_MACHINE_TYPE }}" \
            --var="upstream_machine_type=${{ vars.GCP_UPSTREAM_MACHINE_TYPE }}" \
            --var="tests_machine_type=${{ vars.GCP_TEST_MACHINE_TYPE }}" \
            --auto-approve

      - name: Connect to GKE cluster
        if: ${{ inputs.cloud == 'GCP' }}
        run: |
          gcloud container clusters get-credentials "pt-${{ vars.GCP_CLUSTER_LOCATION }}" \
            --zone "${{ vars.GCP_CLUSTER_LOCATION }}" \
            --project "${{ secrets.GCP_PROJECT }}"
          
          kubectl config rename-context $(kubectl config current-context) performance-testing

      - name: Deploy testing resources
        run: |
          cd deployments
          terraform init -upgrade
          
          # Show terraform plan for debugging
          echo "=== Terraform Plan Output ==="
          terraform plan \
            --var="kubernetes_config_context=performance-testing" \
            --var="cluster_type=${{ env.provider }}" \
            --var="cluster_name=performance-testing" \
            --var="tyk_version=${{ inputs.tyk_version }}" \
            --var="tyk_license=${{ secrets.DASH_LICENSE }}" \
            --var="tyk_profiler_enabled=${{ inputs.tyk_profiler_enabled }}" \
            -out=tfplan 2>&1 | tee plan.log
          
          echo "=== Checking if ConfigMaps will be created ==="
          grep -E "kubernetes_config_map|helm_release.tyk|will be created" plan.log | head -50 || true
          
          echo "=== Checking use_config_maps_for_apis variable ==="
          terraform console -var="kubernetes_config_context=performance-testing" \
            -var="cluster_type=${{ env.provider }}" \
            -var="cluster_name=performance-testing" \
            -var="tyk_version=${{ inputs.tyk_version }}" \
            -var="tyk_license=${{ secrets.DASH_LICENSE }}" \
            -var="tyk_profiler_enabled=${{ inputs.tyk_profiler_enabled }}" <<< "module.deployments.var.use_config_maps_for_apis" 2>&1 || true
          
          # Start background process to monitor pod status
          (while true; do 
            echo "=== Pod Status at $(date) ==="
            kubectl get pods -A --field-selector=status.phase!=Running,status.phase!=Succeeded
            sleep 30
          done) &
          MONITOR_PID=$!
          
          # Apply with detailed logging
          echo "=== Starting Terraform Apply ==="
          terraform apply tfplan 2>&1 | tee terraform-apply.log || (
            echo "=== Terraform Apply Failed ==="
            echo "=== Last 200 lines of terraform apply log ==="
            tail -200 terraform-apply.log
            echo "=== Checking Terraform State ==="
            terraform state list || true
            echo "=== Checking Tyk Module State ==="
            terraform state show module.tyk[0].helm_release.tyk 2>&1 || true
            echo "=== Checking ConfigMaps ==="
            kubectl get configmaps -n tyk || true
            echo "=== Checking Helm Releases ==="
            helm list -n tyk || true
            echo "=== Checking Events in Tyk Namespace ==="
            kubectl get events -n tyk --sort-by='.lastTimestamp' | tail -50 || true
            kill $MONITOR_PID
            exit 1
          )
          
          kill $MONITOR_PID
          
          # Post-deployment validation
          echo "=== Post-Deployment Validation ==="
          echo "=== Terraform State List ==="
          terraform state list | grep -E "(tyk|config_map)" || true
          echo "=== Helm Releases in Tyk Namespace ==="
          helm list -n tyk || true
          echo "=== All Resources in Tyk Namespace ==="
          kubectl get all -n tyk || true
          
          sleep 300

      - name: Debug Tyk Setup
        if: always()
        run: |
          echo "=== Tyk Gateway Pod Status ==="
          kubectl get pods -n tyk -l app.kubernetes.io/name=tyk-gateway
          
          echo "=== Tyk Gateway Pod Logs (last 50 lines) ==="
          kubectl logs -n tyk -l app.kubernetes.io/name=tyk-gateway --tail=50 || true
          
          echo "=== Check ConfigMap ==="
          kubectl get configmap -n tyk tyk-api-definitions -o jsonpath='{.data}' | head -c 1000 || true
          
          echo "=== Check Mounted Files in Pod ==="
          POD=$(kubectl get pods -n tyk -l app.kubernetes.io/name=tyk-gateway -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
          if [ ! -z "$POD" ]; then
            echo "Pod: $POD"
            echo "Files in /mnt/tyk-gateway/apps/:"
            kubectl exec -n tyk $POD -- ls -la /mnt/tyk-gateway/apps/ 2>/dev/null || echo "Directory not found or not mounted"
            echo "Files in /opt/tyk-gateway/apps/:"
            kubectl exec -n tyk $POD -- ls -la /opt/tyk-gateway/apps/ 2>/dev/null || echo "Directory not found"
            
            echo "=== Trigger Tyk Reload ==="
            kubectl exec -n tyk $POD -- curl -H "x-tyk-authorization: foo" http://localhost:8080/tyk/reload 2>/dev/null || echo "Reload failed"
            
            echo "=== Check Loaded APIs ==="
            kubectl exec -n tyk $POD -- curl -H "x-tyk-authorization: foo" http://localhost:8080/tyk/apis 2>/dev/null || echo "Failed to get APIs"
          fi

      - name: Run Tests
        run: |
          cd tests
          terraform init -upgrade
          terraform apply \
            --var="kubernetes_config_context=performance-testing" \
            --auto-approve

      - name: Test Grafana Snapshot
        continue-on-error: true
        run: |
          kubectl logs -n dependencies $(kubectl get pods -n dependencies --selector=app=snapshot-job -o jsonpath='{.items[-1].metadata.name}') --tail=1
      
      - name: Check Scaling Webhook Logs
        continue-on-error: true
        run: |
          echo "=== Scaling Webhook Pod Status ==="
          kubectl get pods -n dependencies -l app=scaling-webhook -o wide
          echo ""
          echo "=== Scaling Webhook Pod Events ==="
          POD_NAME=$(kubectl get pods -n dependencies -l app=scaling-webhook -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
          if [ ! -z "$POD_NAME" ]; then
            kubectl describe pod -n dependencies $POD_NAME | grep -A 10 "Events:" || true
          fi
          echo ""
          echo "=== Scaling Webhook Logs ==="
          kubectl logs -n dependencies -l app=scaling-webhook --tail=200 || echo "No scaling webhook logs found"
          echo ""
          echo "=== Previous Container Logs (if crashed) ==="
          kubectl logs -n dependencies -l app=scaling-webhook --tail=200 --previous 2>/dev/null || echo "No previous container logs"

      - name: Download Profiles
        if: ${{ inputs.tyk_profiler_enabled == true }}
        continue-on-error: true
        run: |
          kubectl port-forward svc/gateway-svc-tyk-tyk-gateway -n tyk 8080 &
          sleep 5

          mkdir profiles
          wget "http://localhost:8080/debug/pprof/heap?debug=1"       -O ./profiles/${{ inputs.tyk_version }}-heap.txt
          wget "http://localhost:8080/debug/pprof/allocs?debug=1"     -O ./profiles/${{ inputs.tyk_version }}-allocs.txt
          wget "http://localhost:8080/debug/pprof/goroutine?debug=1"  -O ./profiles/${{ inputs.tyk_version }}-goroutine.txt

      - name: Upload Profiles
        if: ${{ inputs.tyk_profiler_enabled == true }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.tyk_version }}-profiles
          path: ./profiles
          if-no-files-found: warn

      - name: Destroy Tests
        if: always()
        run: |
          cd tests
          terraform init -upgrade
          terraform destroy \
            --var="kubernetes_config_context=performance-testing" \
            --auto-approve

      - name: Destroy testing resources
        if: always()
        run: |
          cd deployments
          terraform destroy \
            --var="kubernetes_config_context=performance-testing" \
            --var="cluster_type=${{ env.provider }}" \
            --var="cluster_name=performance-testing" \
            --var="tyk_license=${{ secrets.DASH_LICENSE }}" \
            --auto-approve

      - name: Destroy AKS cluster
        if: always() && inputs.cloud == 'Azure'
        run: |
          cd aks
          terraform init -upgrade
          terraform destroy \
            --var="cluster_location=${{ vars.AZURE_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.AZURE_CLUSTER_MACHINE_TYPE }}" \
            --var="upstream_machine_type=${{ vars.AZURE_UPSTREAM_MACHINE_TYPE }}" \
            --var="tests_machine_type=${{ vars.AZURE_TEST_MACHINE_TYPE }}" \
            --auto-approve

      - name: Destroy EKS cluster
        if: always() && inputs.cloud == 'AWS'
        run: |
          cd eks
          terraform init -upgrade
          terraform destroy \
            --var="cluster_location=${{ vars.AWS_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.AWS_CLUSTER_MACHINE_TYPE }}" \
            --var="upstream_machine_type=${{ vars.AWS_UPSTREAM_MACHINE_TYPE }}" \
            --var="tests_machine_type=${{ vars.AWS_TEST_MACHINE_TYPE }}" \
            --auto-approve

      - name: Destroy GKE cluster
        if: always() && inputs.cloud == 'GCP'
        run: |
          cd gke
          terraform init -upgrade
          terraform destroy \
            --var="project=${{ secrets.GCP_PROJECT }}" \
            --var="cluster_location=${{ vars.GCP_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.GCP_CLUSTER_MACHINE_TYPE }}" \
            --var="upstream_machine_type=${{ vars.GCP_UPSTREAM_MACHINE_TYPE }}" \
            --var="tests_machine_type=${{ vars.GCP_TEST_MACHINE_TYPE }}" \
            --auto-approve
