name: GKE Cluster
on:
  workflow_dispatch:
    inputs:
      cluster_ttl:
        description: 'Cluster Time to Live (minutes)'
        required: false
        default: 240
        type: number
jobs:
  cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate into gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Install gcloud k8s auto component
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Stand up GKE cluster
        run: |
          cd gke
          terraform init
          terraform apply \
            --var="project=${{ secrets.GCP_PROJECT }}" \
            --var="cluster_location=${{ vars.GCP_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.GCP_CLUSTER_MACHINE_TYPE }}" \
            --auto-approve

      - name: Results Time to Live Sleep
        run: sleep ${{ inputs.cluster_ttl }}m

      - name: Tear Down cluster
        run: |
          cd gke
          terraform destroy \
            --var="project=${{ secrets.GCP_PROJECT }}" \
            --var="cluster_location=${{ vars.GCP_CLUSTER_LOCATION }}" \
            --var="cluster_machine_type=${{ vars.GCP_CLUSTER_MACHINE_TYPE }}" \
            --auto-approve
